# Generated by Django 3.0.8 on 2020-07-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200707_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.URLField(default='https://github.com/', verbose_name='گیت هاب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_instagram',
            field=models.URLField(default='https://instagram.com/', verbose_name='اینستاگرام ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_telegram',
            field=models.URLField(default='https://t.me/', verbose_name='تلگرام ID'),
        ),
    ]
