# Generated by Django 3.0.8 on 2020-07-06 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=48, verbose_name='دسته بندی')),
                ('cat_slug', models.SlugField(verbose_name='لینک دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='لینک نوشته')),
                ('bmemo', models.TextField(verbose_name='متن بلاگ')),
                ('photo', models.ImageField(upload_to='pic-blog', verbose_name='تصویر بلاگ')),
                ('status', models.CharField(choices=[('v', 'ویژه'), ('f', 'پیش نویس'), ('d', 'درانتظار تایید'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ManyToManyField(to='blog.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
