# Generated by Django 3.0.8 on 2020-07-07 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_prjct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس پروژه')),
                ('memo', models.TextField(verbose_name='توضیحات')),
                ('Stime', models.TimeField(verbose_name='زمان شروع')),
                ('Etime', models.TimeField(verbose_name='زمان پایان')),
                ('price', models.BigIntegerField(verbose_name='قیمت کل')),
                ('status', models.CharField(choices=[('a', 'درحال برسی'), ('b', 'درحال توسعه'), ('d', 'آزمایشی'), ('e', 'منتشر شده')], max_length=1, verbose_name='وضعیت')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='طراح پروژه')),
                ('category', models.ManyToManyField(to='myprojct.cat_prjct', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
